### ISSUE TITLE
Feature request: Add the ability to sort upgrades by certain parameters

### ISSUE THREAD

**Issue by Frizy13** [pastthepixels/InfiniteShooter#5]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to sort upgrades by damage, price, or amount of health added.

**Describe the solution you'd like**
For each option, there will be a corresponding sorting column at the top of the upgrade menu.

**Comment by pastthepixels** [comment]
This is something I think would be useful as well, but since it's a significant change of the UI I think it belongs more in InfiniteShooter 0.5.0. Problem is, though, since I'm planning on adding more ships and lasers I might to do a complete overhaul of the upgrades screen. I'm planning on making it probably styled more like Tyrian ([source port](https://flathub.org/apps/details/com.github.opentyrian.OpenTyrian)).
If InfiniteShooter does add an option to sort upgrades, it'll have to be designed to be keyboard/gamepad-first, which likely means redoing code for SelectSquare.tscn

**Comment by pastthepixels** [comment]
I just wrote some code in `upgrade-list-sorting` that relies on the new UI and should allow for sorting the upgrades menu. I'm not using any built-in functions with the Container node, but I think this is simple and "just works" already so I don't see any point in rewriting it at the moment.

**Comment by pastthepixels** [comment]
Oh and if you want to try it without having to play though a level of the game, you just need to add the line
```gdscript
func _ready(): show_animated()
```
to Upgrades.gd and then selectively run Upgrades.tscn

**Comment by pastthepixels** [comment]
Seeing it as I haven't come across any issues in `upgrade-list-sorting` for a while I think it's good to merge code and close this issue now.
