### ISSUE TITLE
Feature request: Add the ability to adjust the speed of the background movement in the settings.

### ISSUE THREAD

**Issue by Frizy13** [pastthepixels/InfiniteShooter#7]
**Is your feature request related to a problem? Please describe.**
I often find that the background moves too fast, which sometimes makes me feel a little dizzy.

**Describe the solution you'd like**
It would be nice to add an additional option in the settings menu to solve this problem.

**Describe alternatives you've considered**
If you can't add an extra option, you can hardcode the speed of the background in the code itself.

**Comment by pastthepixels** [comment]
I second this, especially since it's rather easy to get dizzy looking at the background. (And can you believe I used to have it at _higher_ speeds for earlier versions of the game?) I think that at the same time I should probably look into other ways to make the background less intensive in general, because it's been bugging me for a while. Maybe adding in some sort of motion blur for the background only would help? I think adding this as well will work to help ease things up for everyone, so I'll create another feature request for that.

**Comment by pastthepixels** [comment]
Also, I think this would fit best as a slider because then it can just be plugged in to [playback_speed](https://docs.godotengine.org/en/stable/classes/class_animationplayer.html#class-animationplayer-property-playback-speed) for the AnimationPlayer responsible for spinning the sky.

**Comment by pastthepixels** [comment]
_Note: Even though there was a PR for this feature (thanks a ton, by the way, and the progress bar with a hint looks really nice!) I still need to iron out some bugs so I'll leave this open until code's merged into `stable` or `feature-additions` if I want to add it in 0.5.0 (but I think since the background can make people feel dizzy I should try to add this in the next point release)_

**Comment by Frizy13** [comment]
I assume the feature already works? Or is there something else that needs to be done to make it stable?

**Comment by pastthepixels** [comment]
Yeah, I've gotten it to a stable state 2 days ago (at least from I've tested). I just haven't gotten the chance to merge it with anything but I'll do that now.

**Comment by pastthepixels** [comment]
Just merged that branch with `stable` so I'll close this now.
